// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMN6DXUwOUQTb9-0FV_Mx_ANeOpOptRMw',
    appId: '1:382928908528:web:d68a31e42a822378c8d235',
    messagingSenderId: '382928908528',
    projectId: 'flutterauth-d67b9',
    authDomain: 'flutterauth-d67b9.firebaseapp.com',
    storageBucket: 'flutterauth-d67b9.firebasestorage.app',
    measurementId: 'G-4RYMQ4MY85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4_Kh9hm6Fg5sbZahX92bEKQ-cNT3J57s',
    appId: '1:382928908528:android:e2711a834779ecaec8d235',
    messagingSenderId: '382928908528',
    projectId: 'flutterauth-d67b9',
    storageBucket: 'flutterauth-d67b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBH_Y0-jDp7oWHo_UWtRj4Lk3Egfa3zSM',
    appId: '1:382928908528:ios:8d506061e5670747c8d235',
    messagingSenderId: '382928908528',
    projectId: 'flutterauth-d67b9',
    storageBucket: 'flutterauth-d67b9.firebasestorage.app',
    iosBundleId: 'com.example.yo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBH_Y0-jDp7oWHo_UWtRj4Lk3Egfa3zSM',
    appId: '1:382928908528:ios:8d506061e5670747c8d235',
    messagingSenderId: '382928908528',
    projectId: 'flutterauth-d67b9',
    storageBucket: 'flutterauth-d67b9.firebasestorage.app',
    iosBundleId: 'com.example.yo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMN6DXUwOUQTb9-0FV_Mx_ANeOpOptRMw',
    appId: '1:382928908528:web:423e1c82e07d19efc8d235',
    messagingSenderId: '382928908528',
    projectId: 'flutterauth-d67b9',
    authDomain: 'flutterauth-d67b9.firebaseapp.com',
    storageBucket: 'flutterauth-d67b9.firebasestorage.app',
    measurementId: 'G-95HQNJJLLF',
  );
}
